# Generated by Django 6.0.3 on 2026-04-07 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
                ('usa_corte_madrugada', models.BooleanField(default=False, help_text='Si se marca, los registros antes de las 6:00 AM cuentan como el día anterior.')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_biometrico', models.CharField(max_length=20, unique=True, verbose_name='ID en Checador')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appChecador.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_real', models.DateTimeField(verbose_name='Fecha/Hora del Checador')),
                ('fecha_administrativa', models.DateField(editable=False)),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3)),
                ('hikvision_event_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appChecador.empleado')),
            ],
            options={
                'ordering': ['-fecha_hora_real'],
            },
        ),
    ]
