# Generated by Django 6.0.3 on 2026-04-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0002_alter_empleado_apellido_alter_empleado_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='numero_seguridad_social',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
