# Generated by Django 6.0.3 on 2026-04-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0003_empleado_numero_empleado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_turno', models.CharField(max_length=50, verbose_name='Nombre del Turno')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('tolerancia_entrada', models.IntegerField(default=15, help_text='Minutos de tolerancia para entrada')),
                ('inicio_entrada', models.TimeField(blank=True, help_text='Hora desde la cual se puede empezar a checar entrada', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='minutos_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='retardo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empleado',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='empleados', to='appChecador.horario'),
        ),
    ]
