# Generated by Django 6.0.3 on 2026-04-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0004_horario_registroasistencia_minutos_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
