# Generated by Django 6.0.3 on 2026-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0006_alter_horario_dia_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='usa_corte_madrugada',
            field=models.BooleanField(default=False, help_text='Si se marca y el horario cruza medianoche, las checadas antes de la hora de salida cuentan para el día anterior.'),
        ),
    ]
