# Generated by Django 6.0.3 on 2026-04-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0007_horario_usa_corte_madrugada'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='minimo_minutos_para_contar_extra',
            field=models.IntegerField(default=30, help_text='Minutos minimos despues de la salida para que empiece a contar la primera hora extra.'),
        ),
        migrations.AddField(
            model_name='horario',
            name='minutos_gracia_salida_extra',
            field=models.IntegerField(default=0, help_text='Minutos de gracia despues de la salida antes de evaluar horas extra.'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='horas_extra',
            field=models.IntegerField(default=0),
        ),
    ]
