# Generated by Django 6.0.3 on 2026-04-17 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0008_horario_minimo_minutos_para_contar_extra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_administrativa', models.DateField()),
                ('entrada_real', models.DateTimeField(blank=True, null=True)),
                ('salida_real', models.DateTimeField(blank=True, null=True)),
                ('retardo', models.BooleanField(default=False)),
                ('minutos_retardo', models.IntegerField(default=0)),
                ('minutos_extra', models.IntegerField(default=0)),
                ('horas_extra', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='appChecador.empleado')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appChecador.horario')),
            ],
            options={
                'ordering': ['-fecha_administrativa', '-entrada_real'],
                'unique_together': {('empleado', 'fecha_administrativa')},
            },
        ),
    ]
