# Generated by Django 6.0.3 on 2026-04-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0009_jornadaasistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='minutos_gracia_salida_extra',
        ),
    ]
