# Generated by Django 6.0.3 on 2026-04-17 22:16

import django.db.models.deletion
from django.db import migrations, models


def copiar_horario_principal(apps, schema_editor):
    Empleado = apps.get_model('appChecador', 'Empleado')
    for empleado in Empleado.objects.all():
        primer_horario = empleado.horarios.first()
        if primer_horario:
            empleado.horario = primer_horario
            empleado.save(update_fields=['horario'])


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0010_remove_horario_minutos_gracia_salida_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_asignados', to='appChecador.horario'),
        ),
        migrations.RunPython(copiar_horario_principal, migrations.RunPython.noop),
    ]
