# Generated by Django 6.0.3 on 2026-04-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0011_empleado_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horarios',
        ),
    ]
