# Generated by Django 6.0.3 on 2026-04-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appChecador', '0012_remove_empleado_horarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='minimo_minutos_para_contar_extra',
            field=models.IntegerField(default=59, help_text='Minutos minimos despues de la salida para que empiece a contar la primera hora extra.'),
        ),
    ]
